// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3K9IeTKKraVF71Dm8E8esLeDm4zqpPmU',
    appId: '1:569003417054:web:7092a86eb30f18678f514f',
    messagingSenderId: '569003417054',
    projectId: 'mealify-dev',
    authDomain: 'mealify-dev.firebaseapp.com',
    storageBucket: 'mealify-dev.appspot.com',
    measurementId: 'G-005NGCRP3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4SJRdVgwyn4otszI2fJlhq8AiHoHZUAs',
    appId: '1:569003417054:android:945d8cb5e0ad06da8f514f',
    messagingSenderId: '569003417054',
    projectId: 'mealify-dev',
    storageBucket: 'mealify-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAHghzUtra7tvbI-JhE76_RoENl4WiQLE',
    appId: '1:569003417054:ios:f936989613f9333f8f514f',
    messagingSenderId: '569003417054',
    projectId: 'mealify-dev',
    storageBucket: 'mealify-dev.appspot.com',
    iosClientId: '569003417054-vdrrbqe3krcsc5j28kgqmioo757bbjff.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAHghzUtra7tvbI-JhE76_RoENl4WiQLE',
    appId: '1:569003417054:ios:f936989613f9333f8f514f',
    messagingSenderId: '569003417054',
    projectId: 'mealify-dev',
    storageBucket: 'mealify-dev.appspot.com',
    iosClientId: '569003417054-vdrrbqe3krcsc5j28kgqmioo757bbjff.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );
}
